//
//  VoiceSettings.swift
//  Wanda
//

import AVFoundation

/// A voice Wanda can speak with: an Apple voice installed on this Mac, or a Kokoro AI
/// voice generated by Wanda's server.
struct VoiceOption: Identifiable, Hashable, Sendable {
    enum Engine: Sendable {
        case apple
        case kokoro
    }

    enum Quality: Int, Comparable, Sendable {
        case standard = 1, enhanced, premium

        static func < (lhs: Quality, rhs: Quality) -> Bool { lhs.rawValue < rhs.rawValue }

        var label: String {
            switch self {
            case .standard: return "Standard"
            case .enhanced: return "Enhanced"
            case .premium: return "Premium"
            }
        }
    }

    static let kokoroPrefix = "kokoro:"
    /// Wanda's default voice when Kokoro is available.
    static let defaultKokoroVoiceID = kokoroPrefix + "af_nova"

    let id: String
    let name: String
    let language: String
    let quality: Quality
    let engine: Engine
    /// Shown next to the name, e.g. "American English, female".
    let detail: String
    let recommended: Bool

    init(
        id: String, name: String, language: String, quality: Quality,
        engine: Engine = .apple, detail: String? = nil, recommended: Bool = false
    ) {
        self.id = id
        self.name = name
        self.language = language
        self.quality = quality
        self.engine = engine
        self.detail = detail ?? Locale.current.localizedString(forIdentifier: language) ?? language
        self.recommended = recommended
    }

    init(kokoro voice: KokoroVoice) {
        self.init(
            id: Self.kokoroPrefix + voice.id,
            name: voice.name,
            language: voice.language,
            quality: .premium,
            engine: .kokoro,
            detail: "\(voice.languageName), \(voice.gender)",
            recommended: voice.recommended
        )
    }

    var isEnglish: Bool { language.lowercased().hasPrefix("en") }

    /// The server-side name for a Kokoro voice ID ("kokoro:af_heart" -> "af_heart").
    static func kokoroName(from id: String?) -> String? {
        guard let id, id.hasPrefix(kokoroPrefix) else { return nil }
        return String(id.dropFirst(kokoroPrefix.count))
    }

    /// Best default: Kokoro's Nova if the server offers it, then another recommended Kokoro
    /// voice, otherwise the highest quality US English Apple voice, preferring Ava on ties.
    static func preferred(from voices: [VoiceOption]) -> VoiceOption? {
        if let nova = voices.first(where: { $0.id == defaultKokoroVoiceID }) {
            return nova
        }
        if let kokoro = voices.first(where: { $0.engine == .kokoro && $0.recommended && $0.isEnglish }) {
            return kokoro
        }
        let apple = voices.filter { $0.engine == .apple }
        let english = apple.filter { $0.language == "en-US" }
        return (english.isEmpty ? apple : english).max { lhs, rhs in
            (lhs.quality.rawValue, lhs.name.hasPrefix("Ava") ? 1 : 0)
                < (rhs.quality.rawValue, rhs.name.hasPrefix("Ava") ? 1 : 0)
        }
    }

    /// Installed Apple voices, minus novelty voices (Bells, Bubbles, …).
    static func installedAppleVoices() -> [VoiceOption] {
        AVSpeechSynthesisVoice.speechVoices()
            .filter { voice in
                if #available(macOS 14.0, *) {
                    return !voice.voiceTraits.contains(.isNoveltyVoice)
                }
                return true
            }
            .map { voice in
                VoiceOption(
                    id: voice.identifier,
                    name: voice.name,
                    language: voice.language,
                    quality: Quality(rawValue: voice.quality.rawValue) ?? .standard
                )
            }
            .sorted { ($0.language, $0.name) < ($1.language, $1.name) }
    }
}

/// The user's voice choices, saved between launches.
@MainActor
final class VoiceSettings: ObservableObject {
    static let rateRange: ClosedRange<Float> = 0.35...0.65
    static let pitchRange: ClosedRange<Float> = 0.75...1.5

    private enum Key {
        static let voiceID = "WandaVoiceIdentifier"
        static let userChoseVoice = "WandaVoiceChosenByUser"
        static let rate = "WandaVoiceRate"
        static let pitch = "WandaVoicePitch"
        static let lowersMusic = "WandaLowersMusic"
        static let pausesMusic = "WandaPausesMusicWhileListening"
    }

    /// nil until the first load finishes.
    @Published private(set) var voices: [VoiceOption]?
    /// True when macOS didn't return its voice list in time (its voice service can hang).
    @Published private(set) var appleVoicesTimedOut = false
    /// True when Wanda's server didn't provide Kokoro voices (not running, or no model files).
    @Published private(set) var kokoroUnavailable = false
    @Published private(set) var voiceID: String? {
        didSet { defaults.set(voiceID, forKey: Key.voiceID) }
    }
    @Published var rate: Float {
        didSet { defaults.set(rate, forKey: Key.rate) }
    }
    @Published var pitch: Float {
        didSet { defaults.set(pitch, forKey: Key.pitch) }
    }
    /// Turn Spotify and Apple Music down while Wanda speaks.
    @Published var lowersMusic: Bool {
        didSet { defaults.set(lowersMusic, forKey: Key.lowersMusic) }
    }
    /// Pause Spotify and Apple Music while the user talks, until Wanda has answered.
    @Published var pausesMusic: Bool {
        didSet { defaults.set(pausesMusic, forKey: Key.pausesMusic) }
    }

    private let api: WandaAPIClient
    private let defaults: UserDefaults

    init(api: WandaAPIClient = WandaAPIClient(), defaults: UserDefaults = .standard) {
        self.api = api
        self.defaults = defaults
        voiceID = defaults.string(forKey: Key.voiceID)
        rate = (defaults.object(forKey: Key.rate) as? Float) ?? AVSpeechUtteranceDefaultSpeechRate
        pitch = (defaults.object(forKey: Key.pitch) as? Float) ?? 1.0
        lowersMusic = (defaults.object(forKey: Key.lowersMusic) as? Bool) ?? true
        pausesMusic = (defaults.object(forKey: Key.pausesMusic) as? Bool) ?? true
    }

    var selectedVoice: VoiceOption? {
        voices?.first { $0.id == voiceID }
    }

    /// The selected Kokoro voice's server name, or nil for an Apple voice.
    var kokoroVoiceName: String? {
        VoiceOption.kokoroName(from: voiceID)
    }

    /// Kokoro's speed multiplier matching the Speed slider (1.0 at the default rate).
    var kokoroSpeed: Float {
        rate / AVSpeechUtteranceDefaultSpeechRate
    }

    /// Called when the user picks a voice; from then on Wanda won't change it automatically.
    func choose(_ id: String?) {
        voiceID = id
        defaults.set(true, forKey: Key.userChoseVoice)
    }

    /// Loads Kokoro voices from the server and Apple voices from macOS, then picks the
    /// best default unless the user has chosen a voice that is still available.
    func loadVoices(appleTimeout: Duration = .seconds(6)) async {
        async let kokoro = loadKokoroVoices()
        async let apple = loadAppleVoices(timeout: appleTimeout)
        let (kokoroVoices, appleVoices) = await (kokoro, apple)

        kokoroUnavailable = kokoroVoices == nil
        appleVoicesTimedOut = appleVoices == nil
        let all = (kokoroVoices ?? []) + (appleVoices ?? [])
        voices = all

        let userChose = defaults.bool(forKey: Key.userChoseVoice)
        if !all.isEmpty, selectedVoice == nil || !userChose,
           let best = VoiceOption.preferred(from: all) {
            voiceID = best.id
        }
    }

    func resetSpeedAndPitch() {
        rate = AVSpeechUtteranceDefaultSpeechRate
        pitch = 1.0
    }

    private func loadKokoroVoices() async -> [VoiceOption]? {
        guard let voices = try? await api.kokoroVoices() else { return nil }
        return voices.map(VoiceOption.init(kokoro:))
    }

    /// Listing Apple voices asks a macOS background service that can stop responding,
    /// so race it against a timeout. (A task group would wait for the stuck lookup too.)
    private func loadAppleVoices(timeout: Duration) async -> [VoiceOption]? {
        final class Once { var resumed = false }
        let once = Once()
        return await withCheckedContinuation { continuation in
            @MainActor func finish(_ result: [VoiceOption]?) {
                guard !once.resumed else { return }
                once.resumed = true
                continuation.resume(returning: result)
            }
            Task.detached(priority: .userInitiated) {
                let voices = VoiceOption.installedAppleVoices()
                await finish(voices)
            }
            Task {
                try? await Task.sleep(for: timeout)
                finish(nil)
            }
        }
    }
}
