//
//  WandaVoice.swift
//  Wanda
//

import AVFoundation
import NaturalLanguage

/// Reads Wanda's replies aloud with the voice, speed and pitch in `VoiceSettings`.
/// Kokoro voices are generated by Wanda's server one sentence at a time, so speech starts
/// after the first sentence instead of the whole reply; if the server fails, the rest is
/// read by an Apple voice. Keep one instance alive; stopping it stops all speech.
///
/// While speaking it publishes a loudness `level` and a `wordCount` that ticks on each
/// word, which the minimal view's logo animates to.
@MainActor
final class WandaVoice: NSObject, ObservableObject {
    @Published private(set) var isSpeaking = false
    /// Loudness from 0 to 1, updated about 30 times a second while speaking.
    @Published private(set) var level: Float = 0
    /// Goes up by one as each word starts.
    @Published private(set) var wordCount = 0
    /// Playback volume from 0 to 1 for Wanda's speech only.
    var volume: Float = 1

    let settings: VoiceSettings
    private let api: WandaAPIClient
    private let synthesizer = AVSpeechSynthesizer()
    private let player = ClipPlayer()
    private var kokoroTask: Task<Void, Never>?
    private var meterTimer: Timer?
    /// Bumped on every speak/stop so callbacks from earlier speech are ignored.
    private var speechID = 0
    private var appleSpeechID = -1
    /// For spotting word starts in Kokoro audio: speech rarely goes silent between
    /// words, so a word is a rise of `onsetRise` above the dip before it.
    private let onsetRise: Float = 0.05
    private var trough: Float = 0
    private var peak: Float = 0
    private var armed = true

    init(settings: VoiceSettings, api: WandaAPIClient = WandaAPIClient()) {
        self.settings = settings
        self.api = api
        super.init()
        synthesizer.delegate = self
    }

    func speak(_ text: String) {
        stop()
        let spoken = SpeechText.clean(text)
        guard !spoken.isEmpty else { return }
        let id = speechID
        setSpeaking(true)
        if let kokoroVoice = settings.kokoroVoiceName {
            kokoroTask = Task {
                let handedToApple = await speakWithKokoro(spoken, voice: kokoroVoice)
                if id == speechID, !handedToApple { setSpeaking(false) }
            }
        } else {
            speakWithApple(spoken)
        }
    }

    func preview() {
        let name = settings.selectedVoice?.name ?? "Wanda"
        speak("Hi, I'm Wanda, speaking with the \(name) voice. How does this sound?")
    }

    func stop() {
        speechID += 1
        kokoroTask?.cancel()
        kokoroTask = nil
        player.stop()
        synthesizer.stopSpeaking(at: .immediate)
        setSpeaking(false)
    }

    /// Returns true if it switched to an Apple voice partway (the Apple voice then
    /// reports when it's done).
    private func speakWithKokoro(_ text: String, voice: String) async -> Bool {
        let chunks = SpeechText.sentences(text)
        let speed = settings.kokoroSpeed
        func fetch(_ chunk: String) -> Task<Data, Error> {
            Task { try await api.speech(text: chunk, voice: voice, speed: speed) }
        }

        var next: Task<Data, Error>? = fetch(chunks[0])
        defer { next?.cancel() }
        for index in chunks.indices {
            do {
                let audio = try await next!.value
                // Generate the next sentence while this one plays.
                next = index + 1 < chunks.count ? fetch(chunks[index + 1]) : nil
                try await player.play(audio, volume: volume)
            } catch {
                guard !Task.isCancelled else { return false }
                // Server down or Kokoro failed: finish the reply with an Apple voice.
                speakWithApple(chunks[index...].joined(separator: " "))
                return true
            }
        }
        return false
    }

    private func speakWithApple(_ text: String) {
        let utterance = AVSpeechUtterance(string: text)
        // A Kokoro ID isn't an Apple voice, so this falls back to the default US voice.
        utterance.voice = settings.voiceID.flatMap(AVSpeechSynthesisVoice.init(identifier:))
            ?? AVSpeechSynthesisVoice(language: "en-US")
        utterance.rate = settings.rate
        utterance.pitchMultiplier = settings.pitch
        utterance.volume = volume
        appleSpeechID = speechID
        synthesizer.speak(utterance)
    }

    // MARK: Animation data

    private func setSpeaking(_ speaking: Bool) {
        guard speaking != isSpeaking else { return }
        isSpeaking = speaking
        meterTimer?.invalidate()
        meterTimer = nil
        level = 0
        trough = 0
        peak = 0
        armed = true
        guard speaking else { return }
        let timer = Timer(timeInterval: 1.0 / 30, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.updateLevel() }
        }
        RunLoop.main.add(timer, forMode: .common)
        meterTimer = timer
    }

    private func updateLevel() {
        guard isSpeaking else { return }
        if let measured = player.level {
            // Kokoro audio: follow its loudness and count a word at each dip-then-rise.
            if armed {
                trough = min(trough, measured)
                if measured > trough + onsetRise, measured > 0.2 {
                    wordCount += 1
                    armed = false
                    peak = measured
                }
            } else {
                peak = max(peak, measured)
                if measured < peak - onsetRise / 2 {
                    armed = true
                    trough = measured
                }
            }
            level = measured
        } else {
            // Apple voices report words directly (see the delegate); fade between them.
            level = max(0, level * 0.82)
        }
    }

    fileprivate func appleWordStarted() {
        guard isSpeaking, appleSpeechID == speechID else { return }
        wordCount += 1
        level = 1
    }

    fileprivate func appleSpeechEnded() {
        guard appleSpeechID == speechID, !synthesizer.isSpeaking else { return }
        setSpeaking(false)
    }
}

extension WandaVoice: AVSpeechSynthesizerDelegate {
    nonisolated func speechSynthesizer(
        _ synthesizer: AVSpeechSynthesizer, willSpeakRangeOfSpeechString characterRange: NSRange,
        utterance: AVSpeechUtterance
    ) {
        Task { @MainActor in self.appleWordStarted() }
    }

    nonisolated func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didFinish utterance: AVSpeechUtterance) {
        Task { @MainActor in self.appleSpeechEnded() }
    }
}

enum SpeechText {
    /// Makes a reply sound natural read aloud: math becomes words ("A equals pi r
    /// squared"), Markdown symbols (`**bold**`, `# headings`, code ticks, bullets, links)
    /// are removed, and line breaks become pauses.
    static func clean(_ text: String) -> String {
        // Math first (it needs the backslashes and braces), then Markdown.
        let text = MathText.spoken(text)
        let rules: [(pattern: String, replacement: String)] = [
            (#"\[([^\]]+)\]\([^)]+\)"#, "$1"),          // [label](url) -> label
            (#"\b(degrees) ?[FC]\b"#, "$1"),                // 72°F (already "72 degrees F") -> 72 degrees
            (#"```[A-Za-z]*"#, ""),                     // code fences
            (#"(?m)^[ \t]*(?:[-•*]|\d+\.)[ \t]+"#, ""),  // list bullets and numbers
            (#"[*`#>]+"#, ""),                          // emphasis, code, headings, quotes
            (#"([^.!?:;,\s])[ \t]*\n+"#, "$1. "),        // line break without punctuation -> pause
            (#"\s+"#, " "),
        ]
        var result = text
        for rule in rules {
            result = result.replacingOccurrences(of: rule.pattern, with: rule.replacement, options: .regularExpression)
        }
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Splits text into sentences, joining short ones ("Sure!") with the next so each
    /// request to the server is worth the round trip.
    static func sentences(_ text: String, minLength: Int = 25) -> [String] {
        let tokenizer = NLTokenizer(unit: .sentence)
        tokenizer.string = text
        var chunks: [String] = []
        var pending = ""
        tokenizer.enumerateTokens(in: text.startIndex..<text.endIndex) { range, _ in
            let sentence = text[range].trimmingCharacters(in: .whitespacesAndNewlines)
            guard !sentence.isEmpty else { return true }
            pending = pending.isEmpty ? sentence : pending + " " + sentence
            if pending.count >= minLength {
                chunks.append(pending)
                pending = ""
            }
            return true
        }
        if !pending.isEmpty { chunks.append(pending) }
        return chunks.isEmpty ? [text] : chunks
    }
}

/// Plays one audio clip at a time and lets callers await the end of playback.
@MainActor
private final class ClipPlayer: NSObject, AVAudioPlayerDelegate {
    struct PlaybackFailed: Error {}

    private var player: AVAudioPlayer?
    private var continuation: CheckedContinuation<Void, Error>?

    func play(_ data: Data, volume: Float = 1) async throws {
        stop()
        let player = try AVAudioPlayer(data: data)
        player.volume = volume
        player.delegate = self
        player.isMeteringEnabled = true
        self.player = player
        try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                self.continuation = continuation
                if !player.play() { finish(PlaybackFailed()) }
            }
        } onCancel: {
            Task { @MainActor in self.stop() }
        }
    }

    func stop() {
        player?.stop()
        player = nil
        finish(CancellationError())
    }

    /// Current loudness from 0 to 1, or nil when no clip is playing.
    var level: Float? {
        guard let player, player.isPlaying else { return nil }
        player.updateMeters()
        let decibels = player.averagePower(forChannel: 0)   // about -60 (quiet) to 0 (loud)
        return min(max((decibels + 45) / 45, 0), 1)
    }

    private func finish(_ error: Error?) {
        guard let continuation else { return }
        self.continuation = nil
        if let error {
            continuation.resume(throwing: error)
        } else {
            continuation.resume()
        }
    }

    nonisolated func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully flag: Bool) {
        Task { @MainActor in self.finish(flag ? nil : PlaybackFailed()) }
    }

    nonisolated func audioPlayerDecodeErrorDidOccur(_ player: AVAudioPlayer, error: Error?) {
        Task { @MainActor in self.finish(error ?? PlaybackFailed()) }
    }
}
