//
//  WandaVoice.swift
//  Wanda
//

import AVFoundation
import NaturalLanguage

/// Reads Wanda's replies aloud with the voice, speed and pitch in `VoiceSettings`.
/// Kokoro voices are generated by Wanda's server one sentence at a time, so speech starts
/// after the first sentence instead of the whole reply; if the server fails, the rest is
/// read by an Apple voice. Keep one instance alive; stopping it stops all speech.
@MainActor
final class WandaVoice {
    let settings: VoiceSettings
    private let api: WandaAPIClient
    private let synthesizer = AVSpeechSynthesizer()
    private let player = ClipPlayer()
    private var kokoroTask: Task<Void, Never>?

    init(settings: VoiceSettings, api: WandaAPIClient = WandaAPIClient()) {
        self.settings = settings
        self.api = api
    }

    func speak(_ text: String) {
        stop()
        let spoken = SpeechText.clean(text)
        guard !spoken.isEmpty else { return }
        if let kokoroVoice = settings.kokoroVoiceName {
            kokoroTask = Task { await speakWithKokoro(spoken, voice: kokoroVoice) }
        } else {
            speakWithApple(spoken)
        }
    }

    func preview() {
        let name = settings.selectedVoice?.name ?? "Wanda"
        speak("Hi, I'm Wanda, speaking with the \(name) voice. How does this sound?")
    }

    func stop() {
        kokoroTask?.cancel()
        kokoroTask = nil
        player.stop()
        synthesizer.stopSpeaking(at: .immediate)
    }

    private func speakWithKokoro(_ text: String, voice: String) async {
        let chunks = SpeechText.sentences(text)
        let speed = settings.kokoroSpeed
        func fetch(_ chunk: String) -> Task<Data, Error> {
            Task { try await api.speech(text: chunk, voice: voice, speed: speed) }
        }

        var next: Task<Data, Error>? = fetch(chunks[0])
        defer { next?.cancel() }
        for index in chunks.indices {
            do {
                let audio = try await next!.value
                // Generate the next sentence while this one plays.
                next = index + 1 < chunks.count ? fetch(chunks[index + 1]) : nil
                try await player.play(audio)
            } catch {
                guard !Task.isCancelled else { return }
                // Server down or Kokoro failed: finish the reply with an Apple voice.
                speakWithApple(chunks[index...].joined(separator: " "))
                return
            }
        }
    }

    private func speakWithApple(_ text: String) {
        let utterance = AVSpeechUtterance(string: text)
        // A Kokoro ID isn't an Apple voice, so this falls back to the default US voice.
        utterance.voice = settings.voiceID.flatMap(AVSpeechSynthesisVoice.init(identifier:))
            ?? AVSpeechSynthesisVoice(language: "en-US")
        utterance.rate = settings.rate
        utterance.pitchMultiplier = settings.pitch
        synthesizer.speak(utterance)
    }
}

enum SpeechText {
    /// Removes Markdown the chat model uses (`**bold**`, `# headings`, code ticks, list
    /// bullets, links) so symbols aren't read aloud, and pauses at line breaks.
    static func clean(_ text: String) -> String {
        let rules: [(pattern: String, replacement: String)] = [
            (#"\[([^\]]+)\]\([^)]+\)"#, "$1"),          // [label](url) -> label
            (#"```[A-Za-z]*"#, ""),                     // code fences
            (#"(?m)^[ \t]*(?:[-•*]|\d+\.)[ \t]+"#, ""),  // list bullets and numbers
            (#"[*`#>]+"#, ""),                          // emphasis, code, headings, quotes
            (#"([^.!?:;,\s])[ \t]*\n+"#, "$1. "),        // line break without punctuation -> pause
            (#"\s+"#, " "),
        ]
        var result = text
        for rule in rules {
            result = result.replacingOccurrences(of: rule.pattern, with: rule.replacement, options: .regularExpression)
        }
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Splits text into sentences, joining short ones ("Sure!") with the next so each
    /// request to the server is worth the round trip.
    static func sentences(_ text: String, minLength: Int = 25) -> [String] {
        let tokenizer = NLTokenizer(unit: .sentence)
        tokenizer.string = text
        var chunks: [String] = []
        var pending = ""
        tokenizer.enumerateTokens(in: text.startIndex..<text.endIndex) { range, _ in
            let sentence = text[range].trimmingCharacters(in: .whitespacesAndNewlines)
            guard !sentence.isEmpty else { return true }
            pending = pending.isEmpty ? sentence : pending + " " + sentence
            if pending.count >= minLength {
                chunks.append(pending)
                pending = ""
            }
            return true
        }
        if !pending.isEmpty { chunks.append(pending) }
        return chunks.isEmpty ? [text] : chunks
    }
}

/// Plays one audio clip at a time and lets callers await the end of playback.
@MainActor
private final class ClipPlayer: NSObject, AVAudioPlayerDelegate {
    struct PlaybackFailed: Error {}

    private var player: AVAudioPlayer?
    private var continuation: CheckedContinuation<Void, Error>?

    func play(_ data: Data) async throws {
        stop()
        let player = try AVAudioPlayer(data: data)
        player.delegate = self
        self.player = player
        try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                self.continuation = continuation
                if !player.play() { finish(PlaybackFailed()) }
            }
        } onCancel: {
            Task { @MainActor in self.stop() }
        }
    }

    func stop() {
        player?.stop()
        player = nil
        finish(CancellationError())
    }

    private func finish(_ error: Error?) {
        guard let continuation else { return }
        self.continuation = nil
        if let error {
            continuation.resume(throwing: error)
        } else {
            continuation.resume()
        }
    }

    nonisolated func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully flag: Bool) {
        Task { @MainActor in self.finish(flag ? nil : PlaybackFailed()) }
    }

    nonisolated func audioPlayerDecodeErrorDidOccur(_ player: AVAudioPlayer, error: Error?) {
        Task { @MainActor in self.finish(error ?? PlaybackFailed()) }
    }
}
